#include "n2s/io/case_json.hpp"
#include "n2s/trim/triangulation.hpp"
#include "n2s/trim/validate.hpp"

#include <catch2/catch_test_macros.hpp>

#include <algorithm>
#include <filesystem>
#include <string>
#include <vector>

namespace {

std::vector<std::filesystem::path> committed_cases() {
    const std::filesystem::path directory{N2S_DATA_DIR};
    std::vector<std::filesystem::path> files;
    if (!std::filesystem::exists(directory)) {
        return files;
    }
    for (const auto& entry : std::filesystem::directory_iterator{directory}) {
        if (entry.is_regular_file() && entry.path().extension() == ".json") {
            files.push_back(entry.path());
        }
    }
    std::sort(files.begin(), files.end());
    return files;
}

} // namespace

TEST_CASE("every committed case file loads and triangulates", "[io][case][data]") {
    // The committed cases are generated by `nurbs2subd export-cases`, so this
    // is the test that catches a change to the case definitions or to the
    // schema silently invalidating what is on disk.
    const std::vector<std::filesystem::path> files = committed_cases();
    REQUIRE_FALSE(files.empty());

    for (const std::filesystem::path& file : files) {
        INFO("case file " << file.string());

        n2s::io::Case loaded = n2s::io::read_case(file);
        CHECK_FALSE(loaded.name.empty());

        const n2s::TrimReport report = n2s::validate_and_repair(loaded.region);
        INFO(report.to_string());
        REQUIRE(report.ok());
        // Exported files are already repaired, so loading one should need no
        // further fixing. A repair here means export wrote something it should
        // not have.
        CHECK(report.repairs.empty());

        const n2s::DomainMesh mesh = n2s::triangulate(loaded.region, loaded.surface);
        CHECK(mesh.triangles.size() > 8);

        // Every case ships explicit colour ranges, so no figure drawn from one
        // is auto-ranged by default.
        CHECK_FALSE(loaded.color_ranges.empty());
    }
}

TEST_CASE("committed case files stay small", "[io][case][data]") {
    // CLAUDE.md caps data/ at 1 MB per file. Cases are generated, so it would
    // be easy to raise a sampling parameter and quietly commit megabytes.
    for (const std::filesystem::path& file : committed_cases()) {
        INFO(file.string());
        CHECK(std::filesystem::file_size(file) < 1024u * 1024u);
    }
}
